### ISSUE TITLE
[Proposal] How to get the config of X30？

### ISSUE THREAD

**Issue by WYYAHYT** [DeepRoboticsLab/Lite3_rl_training#1]
Thanks for sharing the code of  training Lite3. This is a  promising project.

In `Lite3_rl_training/legged_gym/resources/robots`, I see the `urdf file of X30`, but there is **no config of X30 for training**.

I tried to write the config of X30, but I don't know some important parameters of X30, such as `stiffness` and `damping`, the only parameter I can find is the height, which is shown on official web page.

So, could you kindly offer these crucial information of X30? 

A tested training config file would be better.

**Comment by yyang0802** [comment]
Thank you for your attention. The code in this respository is mainly for Lite3. For security reasons, we are not currently releasing the example codes of X30. If you need to train X30, you can contact our aftersales for further communication.
